version: '3.8'
services: 
  database:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=${MONGODB_NAME}
    volumes: 
      - ./my_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  node-web:
    build: 
      context: ./node-web
      dockerfile: Dockerfile
    depends_on: 
      - database
    environment:
      - DB_HOST=database
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_NAME
      - DB_PORT=27017
      - NODE_LOCAL_PORT=$NODE_LOCAL_PORT
      - NODE_DOCKER_PORT=$NODE_DOCKER_PORT
      - AUTH_SECRET_KEY=$AUTH_SECRET_KEY
      - ADMIN_SECRET_KEY=$ADMIN_SECRET_KEY
    volumes: 
      - /app/node_modules
      - ./node-web:/app
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}
  
volumes: 
  my_data: 